const {
  VITE_FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_PROJECT_ID,
  VITE_FIREBASE_STORAGE_BUCKET,
  VITE_FIREBASE_MESSAGING_SENDER_ID,
  VITE_FIREBASE_APP_ID,
  VITE_FIREBASE_MEASUREMENT_ID,
} = import.meta.env;

export const FIREBASE_API_KEY = VITE_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = VITE_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = VITE_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = VITE_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = VITE_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = VITE_FIREBASE_APP_ID;
export const FIREBASE_MEASUREMENT_ID = VITE_FIREBASE_MEASUREMENT_ID;

export const STORAGE_KEY = {
  EMAIL_CACHE_KEY: "vocab_user_email",
};
